# Generated by Django 3.0.8 on 2020-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0004_auto_20200804_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nom Du Categorie'),
        ),
    ]
