# Generated by Django 3.0.8 on 2020-08-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0005_auto_20200805_1536'),
        ('equipement', '0005_auto_20200804_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='equipement_installe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_equipement', to='installation.Installation'),
        ),
    ]
