# Generated by Django 3.0.8 on 2020-08-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0006_auto_20200805_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='equipement_installe',
        ),
    ]
