# Generated by Django 3.0.8 on 2020-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0007_remove_equipement_equipement_installe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='num_serie',
            field=models.CharField(max_length=20),
        ),
    ]
