# Generated by Django 3.0.8 on 2020-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0008_auto_20200813_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='date_ajoute',
            field=models.DateTimeField(max_length=1000),
        ),
    ]
