# Generated by Django 3.0.8 on 2020-09-10 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0009_auto_20200910_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='date_ajoute',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
