# Generated by Django 3.0.8 on 2020-09-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0011_auto_20200910_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='etat_equipement',
            field=models.CharField(choices=[('0', 'Non attribut'), ('1', 'Attribu')], default='0', max_length=15, verbose_name='etat'),
        ),
    ]
