# Generated by Django 3.0.8 on 2020-09-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0012_auto_20200910_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='etat_equipement',
            field=models.CharField(choices=[('0', 'Non attribut'), ('1', 'Attribué')], default='1', max_length=15, verbose_name='etat'),
        ),
    ]
