# Generated by Django 3.0.8 on 2020-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0014_auto_20200910_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='date_ajoute',
            field=models.DateTimeField(),
        ),
    ]
