# Generated by Django 3.0.8 on 2020-08-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_auto_20200803_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='lieu',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='direction',
            name='ville',
            field=models.CharField(max_length=20),
        ),
    ]
