# Generated by Django 3.0.8 on 2020-08-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0003_auto_20200803_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='mac',
            field=models.CharField(max_length=50, verbose_name='Adesse Mac'),
        ),
    ]
