# Generated by Django 3.0.8 on 2020-08-05 13:36

from django.db import migrations
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0004_auto_20200804_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='mac',
            field=macaddress.fields.MACAddressField(integer=True, verbose_name='Adesse Mac'),
        ),
    ]
