# Generated by Django 3.0.8 on 2020-08-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0007_remove_equipement_equipement_installe'),
        ('installation', '0007_installation_equipement_installe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='equipement_installe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_equipement', to='equipement.Equipement'),
        ),
    ]
