# Generated by Django 3.0.8 on 2020-09-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0010_auto_20200910_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='service',
            field=models.CharField(choices=[('0', 'En service'), ('1', 'En panne'), ('1', 'A remplace')], default='0', max_length=15, verbose_name='etat'),
        ),
    ]
