# Generated by Django 3.0.8 on 2020-09-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0011_installation_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='service',
            field=models.CharField(choices=[('En service', '0'), ('1', 'En panne'), ('1', 'A remplace')], default='0', max_length=15, verbose_name='etat'),
        ),
    ]
