# Generated by Django 3.0.8 on 2020-09-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0012_auto_20200912_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='service',
            field=models.CharField(choices=[('En service', 'En service'), ('En panne', 'En panne'), ('A remplace', 'A remplace')], default='En service', max_length=15, verbose_name='etat'),
        ),
    ]
