# Generated by Django 3.0.8 on 2020-09-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0013_auto_20200912_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='service',
            field=models.CharField(choices=[('0', 'En service'), ('1', 'En panne'), ('2', 'A remplace')], default='0', max_length=15, verbose_name='etat'),
        ),
    ]
