# Generated by Django 3.0.8 on 2020-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0015_auto_20200912_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='date_installe',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
