# Generated by Django 3.0.8 on 2020-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0017_auto_20200913_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='date_installe',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='installation',
            name='service',
            field=models.CharField(choices=[('En service', 'En service'), ('En panne', 'En panne')], default='En service', max_length=15),
        ),
    ]
